version: "3"
services:
  cliquebait:
    image: foamspace/cliquebait:latest
    ports:
      - "8545:8545"
  plasma:
    image: docker.kube-system.svc.cluster.local/foam/plasma-mvp-sidechain:latest
    ports:
      - "1317:1317"
