version: "3"
services:
  cliquebait:
    image: foamspace/cliquebait:latest
    ports:
      - "8545:8545"
  plasma:
    image: foamspace/plasma-mvp-sidechain:latest
    ports:
      - "1317:1317"
      - "26657:26657"
    volumes:
    - ./plasma.toml:/root/.plasmad/config/plasma.toml
