plasma_block_commitment_rate = "2s"
is_operator = "true"
ethereum_plasma_contract_address = "0xee9e5ad72d16ab3f45435004e26c6cc4f978a9fa"
ethereum_operator_privatekey = "e1c01c07784956abe9c72eb20ac6f0a075edb3e0f61e833e0855a52c6e7c7037"
ethereum_nodeurl = "http://localhost:8545"
ethereum_finality = "3"