plasma_block_commitment_rate = "2s"
is_operator = "false"
ethereum_plasma_contract_address = "0x9284f22bd1613789ace60c54e9295a480e7a3e1d"
ethereum_operator_privatekey = ""
ethereum_nodeurl = "http://cliquebait:8545"
ethereum_finality = "3"